Repository hmcts/em-ccd-orchestrator, pull requests merged in 2020-09, with the labels that each got.

#392 Added in logging
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiEventCreator.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-392

#389 EM-2747 Adding config for Mutation Tests
  Jenkinsfile_nightly
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-389

#384 Updated nightly build file
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-ccdorc-pr-384

#394 Added in SSCS welsh config file
  src/aat/resources/adv_bundling_functional_tests_ccd_def.xlsx
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-394

#398 EM-2552-Wiring Security ZAP configuration for Nightly Build - CCD Orch.
  Jenkinsfile_nightly
  audit.json
  build.gradle
  security.sh
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/smoke/SmokeTest.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/WelcomeController.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/WelcomeControllerTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-398
