Repository hmcts/em-ccd-orchestrator, pull requests merged in 2020-01, with the labels that each got.

#207 Updated the component name
  Jenkinsfile_CNP
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/requirements.yaml
  charts/em-ccdorc/values.aat.template.yaml
  charts/em-ccdorc/values.preview.template.yaml
  charts/em-ccdorc/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:em-ccdorc-pr-207

#211 EM-2507: Amend ccd spreadsheet to reflect the addition of the enable …
  src/aat/resources/adv_bundling_functional_tests_ccd_def.xlsx
Labels: ns:em-ccd-orchestrator-pr-211

#214 Fix sonar
  build.gradle
Labels: ns:em, rel:em-ccdorc-pr-214

#221 Add support for regex
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
Labels: ns:em, rel:em-ccdorc-pr-221

#227 EM-2526: Implement configuration file map
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-demo-bundle.yaml
Labels: ns:em, rel:em-ccdorc-pr-227

#234 EM-2543: Allow bundles to be created even if files not present
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/main/resources/bundleconfiguration/f-tests-10-invalid-doc-set-property.yaml
  src/main/resources/bundleconfiguration/f-tests-10-sorting.yaml
  src/main/resources/bundleconfiguration/f-tests-11-sorting.yaml
  src/main/resources/bundleconfiguration/f-tests-12-invalid-document-property.yaml
  src/main/resources/bundleconfiguration/f-tests-9-invalid-doc-property.yaml
  src/main/resources/bundleconfiguration/f-tests-9-multiple-filters.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
  src/test/resources/case-data4.json
Labels: ns:em, rel:em-ccdorc-pr-234

#236 retrigger-build-to-fix-url-issue
  README.md
Labels: ns:em, rel:em-ccdorc-pr-236

#238 Regex for sscs bundle
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
Labels: ns:em, rel:em-ccdorc-pr-238

#240 tidy up
  infrastructure/aat.tfvars
  infrastructure/main.tf
Labels: ns:em, rel:em-ccdorc-pr-240
