Repository hmcts/em-ccd-orchestrator, pull requests merged in 2020-05, with the labels that each got.

#329 EM-2593 Append stitched document with pdf suffix
  config/owasp/dependency-check-suppressions.xml
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoaderTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java
Labels: ns:em, rel:em-ccdorc-pr-329

#330 EM-2719: Serenity Reporting CCD-Orchestrator
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/BaseTest.java
Labels: ns:em, rel:em-ccdorc-pr-330

#331 EM-2719: Added Dependency Check suppression for apache_tomcat:apache_t…
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, rel:em-ccdorc-pr-331

#334 Em 2886 integrate pact pipeline
  Jenkinsfile_CNP
  build.gradle
  pacts/em_ccd_orchestrator-idam_api.json
  src/contractTest/java/uk/gov/hmcts/reform/em/orchestrator/IdamConsumerTest.java
Labels: ns:em, rel:em-ccdorc-pr-334

#336 EM-2886 Fix for POST request body generation in pact json
  pacts/em_ccd_orchestrator-idam_api.json
  src/contractTest/java/uk/gov/hmcts/reform/em/orchestrator/IdamConsumerTest.java
Labels: ns:em, rel:em-ccdorc-pr-336

#339 remove installcharts
  Jenkinsfile_CNP
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, rel:em-ccdorc-pr-339
