Repository hmcts/em-ccd-orchestrator, pull requests merged in 2020-06, with the labels that each got.

#342 Added in changes for documentLinkName
  config/owasp/dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfiguration.java
  src/main/resources/bundleconfiguration/iac-bundle-config.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
  src/test/resources/case-data6.json
Labels: ns:em, rel:em-ccdorc-pr-342

#343 Added in another yaml config file
  src/main/resources/bundleconfiguration/iac2-bundle-config.yaml
Labels: ns:em, rel:em-ccdorc-pr-343

#347 Turn off paginationStyle for SSCS
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-347

#348 RIA-3116: IAC final hearing bundling config
  src/main/resources/bundleconfiguration/iac-hearing-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-348

#351 RIA-3116: IAC final hearing bundling config - structured using folders
  src/main/resources/bundleconfiguration/iac-hearing-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-351
