Repository hmcts/em-ccd-orchestrator, pull requests merged in 2020-12, with the labels that each got.

#454 EM-3263 - EM-CCD: Add retry logic for failing functional test cases
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdCloneScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdPrehookScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/retry/RetryRule.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-454

#455 EM-3263- EM-CCD: Add retry logic for failing functional test cases
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdCloneScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdPrehookScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/retry/RetryRule.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-455

#458 EM-3281 - em-ccd-orchestrator API - Suppress nightly jobs dependency …
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-458

#459 Updated vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-459

#464 Resolved vulnerabilities
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-464

#465 EM-3300 - CCD-Orchestrator API - Suppress nightly jobs dependency vul…
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-465

#466 EM-3304-CCD-Orchestrator API - Update local environment setup instruc…
  README.md
Labels: ns:em, prd:em, rel:em-ccdorc-pr-466
