Repository hmcts/em-ccd-orchestrator, pull requests merged in 2020-03, with the labels that each got.

#261 Em 1800 enable image configuration ccd
  config/owasp/dependency-check-suppressions.xml
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/aat/resources/adv_bundling_functional_tests_ccd_def.xlsx
  src/aat/resources/~$adv_bundling_functional_tests_ccd_def.xlsx
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/domain/enumeration/ImageRendering.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/domain/enumeration/ImageRenderingLocation.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/DocumentImage.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/StitchingBundleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/mapper/StitchingDTOMapper.java
  src/main/resources/bundleconfiguration/f-tests-13-render-image-flat-docs.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/mapper/StitchingDTOMapperTest.java
Labels: ns:em, rel:em-ccdorc-pr-261

#239 OpenId Connect Changes
  Jenkinsfile_CNP
  README.md
  bin/idam-authenticate.sh
  bin/idam-client-setup-roles.sh
  bin/idam-client-setup.sh
  bin/start-local-environment.sh
  build.gradle
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
  config/owasp/dependency-check-suppressions.xml
  docker-compose-dependencies.yml
  docker-compose.yml
  idam-client-setup.sh
  infrastructure/demo.tfvars
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/AuthCheckerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityUtils.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/BaseTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/TestSecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCaseDataContentTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/mapper/StitchingDTOMapperTest.java
Labels: ns:em, rel:em-ccdorc-pr-239

#305 EM-1800: Allow only values for Document Image fields that are non emp…
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/DocumentImage.java
  src/main/resources/bundleconfiguration/f-tests-13-render-image-flat-docs.yaml
Labels: ns:em, rel:em-ccdorc-pr-305

#304 Em 2425 bundle config error message
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/resources/automated-case-invalid-configuration.json
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoader.java
  src/main/resources/bundleconfiguration/example-incorrect-key.yaml
  src/main/resources/bundleconfiguration/example-incorrect-value-for-key.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoaderTest.java
Labels: ns:em, rel:em-ccdorc-pr-304

#284 Em 2625 file prefix unique identifier
  src/aat/resources/adv_bundling_functional_tests_ccd_def.xlsx
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/StitchingBundleDTO.java
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoTest.java
Labels: ns:em, rel:em-ccdorc-pr-284

#314 Removed the issuer override bits
  Jenkinsfile_CNP
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
  docker-compose-dependencies.yml
  docker-compose.yml
  infrastructure/demo.tfvars
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java
  src/main/resources/application.yaml
Labels: ns:em, rel:em-ccdorc-pr-314
