Repository hmcts/em-ccd-orchestrator, pull requests merged in 2020-02, with the labels that each got.

#252 Allow date fields for sorting
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
  src/test/resources/case-data5.json
Labels: ns:em, rel:em-ccdorc-pr-252

#253 EM-2395: alter ccd user account name to use valid email and include e…
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
  src/main/resources/bundleconfiguration/f-tests-12-invalid-document-property.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
Labels: ns:em, rel:em-ccdorc-pr-253

#254 EM-2395: Alter email notification field to not use the primitive bool…
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/StitchingBundleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/mapper/StitchingDTOMapper.java
  src/main/resources/bundleconfiguration/example-with-documents.yaml
  src/main/resources/bundleconfiguration/example.yaml
  src/main/resources/bundleconfiguration/f-tests-11-sorting.yaml
  src/main/resources/bundleconfiguration/f-tests-12-invalid-document-property.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoaderTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/mapper/StitchingDTOMapperTest.java
Labels: ns:em, rel:em-ccdorc-pr-254

#256 remove dockerbuild and aadID
  Jenkinsfile_CNP
  charts/em-ccdorc/values.preview.template.yaml
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, rel:em-ccdorc-pr-256

#257 EM-2395: Add check to see if the Boolean wrapper value is null
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackController.java
Labels: ns:em, rel:em-ccdorc-pr-257

#260 Em 2395 alter idam email account used
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
Labels: ns:em, rel:em-ccdorc-pr-260

#264 Temporarily hardcode the idam user so that email notifications can be…
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
Labels: ns:em, rel:em-ccdorc-pr-264

#266 EM-2395: Revert email creation script in CCD Test Helper. This is to …
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
Labels: ns:em, rel:em-ccdorc-pr-266

#267 Use jurisdiction instead of case type id for SSCS
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
Labels: ns:em, rel:em-ccdorc-pr-267

#270 update Javachart. Bump chart ver
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/requirements.yaml
Labels: ns:em, rel:em-ccdorc-pr-270

#251 Em 2574 reorder bundle list
  docker-compose-dependencies.yml
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdCloneScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleCloningService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdCaseUpdater.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleCloningServiceTest.java
Labels: ns:em, rel:em-ccdorc-pr-251
