Repository hmcts/em-ccd-orchestrator, pull requests merged in 2020-11, with the labels that each got.

#434 Updated Spring boot version
  build.gradle
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/requirements.yaml
  charts/em-ccdorc/values.yaml
  config/owasp/dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-434

#444 Updated cnp-module-key-vault branch
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-ccdorc-pr-444

#447 Updated terraform version
  infrastructure/.terraform-version
Labels: ns:em, prd:em, rel:em-ccdorc-pr-447

#424 EM-3130 finalbundling to prehearing
  config/.DS_Store
  config/owasp/dependency-check-suppressions.xml
  src/main/resources/bundleconfiguration/iac-reheard-hearing-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-424

#443 EM-3224_2 EM-CCD: Update functional and smoke test cases to generate …
  .gitignore
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdCloneScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdPrehookScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/smoke/SmokeTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-443

#448 Updated azurerm version
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-ccdorc-pr-448

#449 Removed unused MI variable and values
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-ccdorc-pr-449

#450 Updated em-test-helper version
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-450
