Repository hmcts/em-ccd-orchestrator, pull requests merged in 2020-04, with the labels that each got.

#315 Updated openId endpoint
  Jenkinsfile_CNP
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
Labels: ns:em, rel:em-ccdorc-pr-315

#316 Update complex yaml example to include new features
  src/main/resources/bundleconfiguration/complex-example.yaml
Labels: ns:em, rel:em-ccdorc-pr-316

#311 EM-1781: Migrate int to Integer
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/DocumentImage.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
Labels: ns:em, rel:em-ccdorc-pr-311

#318 Moved secrets to values.yaml
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.aat.template.yaml
  charts/em-ccdorc/values.preview.template.yaml
  charts/em-ccdorc/values.yaml
Labels: ns:em, rel:em-ccdorc-pr-318

#321 Updated Pact test for openId
  README.md
  build.gradle
  docker-pactbroker-compose.yml
  pacts/em_ccd_orchestrator-idam_api.json
  src/contractTest/java/uk/gov/hmcts/reform/em/orchestrator/IdamConsumerTest.java
  target/pacts/em_ccd_orchestrator-idam_api.json
Labels: ns:em, rel:em-ccdorc-pr-321
