Repository hmcts/em-ccd-orchestrator, pull requests merged in 2021-01, with the labels that each got.

#487 Resolved Vulnerabilities
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-487

#473 sscs-8458 New config for edited bundles
  src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-unedited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-unedited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-473

#486 SSCS-8587 Remove .pdf extension from file name
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-486

#491 EM-3428-EM-CCD: Failed to generate serenity report
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-491
