Repository hmcts/em-ccd-orchestrator, pull requests merged in 2021-11, with the labels that each got.

#724 Resolve "CVE-2021-22096"
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-724

#725 Em 4113 resolve vulnerabilities
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-725

#682 Added in CDAM changes using session approach
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  bin/start-local-environment.sh
  build.gradle
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.preview.template.yaml
  docker-compose-dependencies.yml
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/TestConfig.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/dto/CcdTestBundleDocumentDTO.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/dto/CcdTestDocument.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/Constants.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CdamDetailsDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDocumentDTO.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdDocument.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/DocumentTaskDTO.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/StitchingBundleDTO.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java
  src/test/resources/cdampayload.json
Labels: ns:em, prd:em, rel:em-ccdorc-pr-682

#738 Em 3668 remove stitching pr url
  charts/em-ccdorc/values.preview.template.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-738

#739 Fixed fortify issue
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-739

#751 Ignore tests involving CDAM
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-751

#750 Resolve Sonar issues
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfigurationSortOrder.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/domain/enumeration/ImageRendering.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/domain/enumeration/ImageRenderingLocation.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/domain/enumeration/PageNumberFormat.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspect.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-750

#752 Resolved Sonar issues
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommand.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/AutomatedCaseConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiEventCreator.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CallbackException.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-752

#753 Added in Sonar ignore rule in build.gradle
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommand.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiEventCreator.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-753

#754 Resolved Sonar issues
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfigurationSortOrder.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/InputValidationException.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiEventCreator.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-754
