Repository hmcts/em-ccd-orchestrator, pull requests merged in 2021-04, with the labels that each got.

#551 Updated image path
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-551

#556 EM-3684 - CCD-Orchestrator API - Add functional tests for CcdStitchBu…
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdCloneScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-556

#558 EM-3700 - EM-CCD-Orchestrator: Add functional tests for NewBundleCont…
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-558

#564 Updated java chart version
  charts/em-ccdorc/Chart.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-564

#563 SSCS-9002 Remove unedited bundle config
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-unedited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-unedited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-563
