Repository hmcts/em-ccd-orchestrator, pull requests merged in 2021-05, with the labels that each got.

#588 Fixed Resource leak
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/info/BuildInfo.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-588

#594 Added same site cookie vulnerabilities to ignore list
  audit.json
Labels: ns:em, prd:em, rel:em-ccdorc-pr-594

#596 Updated docker-compose-dependencies
  docker-compose-dependencies.yml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-596

#595 Upgraded SpringBoot to 2.4.5
  Jenkinsfile_CNP
  build.gradle
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
  config/owasp/dependency-check-suppressions.xml
  config/pmd/ruleset.xml
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/info/BuildInfo.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-595

#604 Increased httpClient timeout
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/HttpClientConfiguration.java
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-604

#605 Fixed Resource leak
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoader.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-605
