Repository hmcts/em-ccd-orchestrator, pull requests merged in 2021-02, with the labels that each got.

#490 Increased field length restriction
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/Constants.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDTO.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingServiceTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-490

#497 sscs 8622 New config for collection of dwp docs
  src/main/resources/bundleconfiguration/sscs-new-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-unedited-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-welsh-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-welsh-unedited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-497

#507 Resolved vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-507

#508 Overwrite old sscs bundle config with new config
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-unedited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-unedited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-508

#509 Remove deprecated config
  src/main/resources/bundleconfiguration/sscs-new-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-unedited-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-welsh-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-new-bundle-welsh-unedited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-509

#514 Resolved CVE-2021-21290
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-514

#515 Em 3513 update pact jupiter related dependencies
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-515

#516 EM-3526 - CCD-Orch API - Suppress nightly jobs dependency vulnerabili…
  audit.json
Labels: ns:em, prd:em, rel:em-ccdorc-pr-516

#521 Updated terraform and gradle version
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
Labels: ns:em, prd:em, rel:em-ccdorc-pr-521
