Repository hmcts/em-ccd-orchestrator, pull requests merged in 2021-06, with the labels that each got.

#616 Updated em-test-helper version
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-616

#618 Fixed CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-618

#620 Sscs 9290 rip1 in bundle
  build.gradle
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-620

#610 SSCS-9182 Add statement of evidence pdf for audio to bundle
  build.gradle
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-610

#628 Fixed Resource leak issue
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoader.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilitiesTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-628

#632 reorder security.sh
  security.sh
Labels: ns:em, prd:em, rel:em-ccdorc-pr-632
