Repository hmcts/em-ccd-orchestrator, pull requests merged in 2021-12, with the labels that each got.

#760 Enabled sonar check
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-760

#770 Fixed log4J vulnerability
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-770

#771 Updated log4J version
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-771

#772 Reverted Ignore tests involving CDAM change
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-772

#775 Update fortify scan
  Jenkinsfile_nightly
  config/fortify-client.properties
Labels: ns:em, prd:em, rel:em-ccdorc-pr-775
