Repository hmcts/em-ccd-orchestrator, pull requests merged in 2021-03, with the labels that each got.

#522 SSCS-8737 Audio video bundle config
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-unedited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-unedited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-522

#527 Resolved CVE-2021-22112
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-527

#534 Resolved CVE-2021-25122, CVE-2021-25329
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-534

#538 EM-3628 - EM-CCD-Orchestrator: Update Jenkins file to generate Unit t…
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-ccdorc-pr-538

#539 EM-3629 - EM-CCD-Orchestrator: Fix ignored test cases
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdPrehookScenarios.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-539

#541 EM-3640 - EM-CCD-Orchestrator: Pact report not generating
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-541

#540 SSCS-8861 Configure Welsh RIP1 doc for bundle
  src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-unedited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-unedited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-540

#547 Fixed CVE-2020-15824, CVE-2020-29582
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-547

#520 Added Multi bundle implementation
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/aat/resources/custom-documents-case.json
  src/aat/resources/filename-with-51-chars.json
  src/aat/resources/multi-bundle-case.json
  src/aat/resources/non-custom-documents-case.json
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfigurationException.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoader.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/AutomatedCaseConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/Constants.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDTO.java
  src/main/resources/bundleconfiguration/custom-bundle-config.yaml
  src/main/resources/bundleconfiguration/custom-bundle-wrong-config.yaml
  src/main/resources/bundleconfiguration/example-with-51-chars-filename.yaml
  src/main/resources/bundleconfiguration/non-custom-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoaderTest.java
  src/test/resources/case-data-custom.json
Labels: ns:em, prd:em, rel:em-ccdorc-pr-520
