Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-12, with the labels that each got.

#1026 Refactoring the PRL Bundling folders
  src/main/resources/bundleconfiguration/prl-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1026

#1033 EM-3776: Adding test coverage for StitchingCompleteCallbackController
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/StitchingCompleteScenarios.java
  src/aat/resources/stitchingComplete.json
Labels: ns:em, prd:em, Do Not Merge, rel:em-ccdorc-pr-1033

#1037 EM-4884: Removed service jwt token
  src/aat/resources/stitchingComplete.json
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1037

#1031 Refactoring changes for fixes(READY FOR MERGE)
  src/main/resources/bundleconfiguration/prl-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1031
