Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-01, with the labels that each got.

#786 Excluded tests from Sonar
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-786

#787 Updated log4J version
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-787

#792 Upgrade gradle to 7.3.3
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:em, prd:em, rel:em-ccdorc-pr-792

#800 Upgrade Java version to 17
  Dockerfile
  build.gradle
  charts/em-ccdorc/Chart.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-800

#801 Reverted java 17 version changes
  Dockerfile
  bin/start-local-environment.sh
  build.gradle
  docker-compose-dependencies.yml
  src/aat/resources/application.yml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-801

#809 RIA-4926 updated hearing bundle template
  src/main/resources/bundleconfiguration/iac-hearing-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-809
