Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-11, with the labels that each got.

#992 EM-4694 close response
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/HttpOkResponseCloser.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-992

#994 EM-4744 avoid-CVE-2022-31692
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-994

#999 Moved S2S list to values.yaml
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-999

#1000 Whitelisted sptribs_case_api for non-prod environments
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1000

#1002 EM-4790 check response before close
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/HttpOkResponseCloser.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1002

#997 prl bundle config changes(ready for merge)
  src/main/resources/bundleconfiguration/prl-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-997

#1013 Modified prl yaml file as per the new requirements
  src/main/resources/bundleconfiguration/prl-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1013

#1014 Refactoring mappings as per new suggestions
  src/main/resources/bundleconfiguration/prl-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1014
