Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-10, with the labels that each got.

#964 prl bundling test yaml config changes
  config/owasp/dependency-check-suppressions.xml
  src/main/resources/bundleconfiguration/sample-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-964

#965 Whitelisted prl_cos_api to access non-prod env
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-965

#968 pulling master changes into FPET-148
  build.gradle
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-968

#967 path corrected for bundling config changes
  src/main/resources/bundleconfiguration/sample-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-967

#970 EM-3699 return 400 error for bad requests.
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-970

#977 Em-4666 use debug level
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/Application.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/ServiceTokenGeneratorConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityUtils.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspect.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspectTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-977

#980 EM-4666 remove unnecessary app-insight class
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/appinsights/AppInsightsEventRepository.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/appinsights/AppInsightsEvents.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/appinsights/EventRepository.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdater.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-980

#982 EM-4666 use debug level for app-insight
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-982

#983 EM-4691 remove unnecessary log config
  build.gradle
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
  src/main/resources/logback-spring.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-983
