Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-06, with the labels that each got.

#889 Resolved CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-889

#890 Fix CVE-2022-22978
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-890

#892 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-892

#894 Updated the logic to log the caseId for each request
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/Constants.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyHttpServletRequest.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyServletInputStream.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ContentCachingFilter.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspect.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyHttpServletRequestUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyServletInputStreamUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ContentCachingFilterUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspectTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-894

#896 Suppressed CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-896
