Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-03, with the labels that each got.

#820 SSCS-10147changed folder name
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-820

#830 update postgres version to 11 for local setup
  database/Dockerfile
  docker-compose-dependencies.yml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-830

#832 bump java chart
  charts/em-ccdorc/Chart.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-832

#831 Upgraded SpringBoot version to 2.6.4
  build.gradle
  config/owasp/dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/Application.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-831

#840 added "100000_A Client Error response code was returned by the server…
  audit.json
Labels: ns:em, prd:em, rel:em-ccdorc-pr-840

#844 Nightly build Security Scan fix
  audit.json
  security.sh
Labels: ns:em, prd:em, rel:em-ccdorc-pr-844

#847 Changed fasterXmlJackson version from 2.12.5 to 2.13.2
  build.gradle
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdaterTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-847

#848 Fix the failing test in CcdCallbackBundleUpdaterTest
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdaterTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-848

#849 Updated dependabot.yml
  .github/dependabot.yml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-849

#853 EM-4341 - added: jackson-databind version to manually be set to 2.13.…
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-853

#856 Remove jackson-bom
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-856

#857 Updated azurerm and terraform version
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/versions.tf
Labels: ns:em, prd:em, rel:em-ccdorc-pr-857
