Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-09, with the labels that each got.

#913 Updated renovate config
  .github/renovate.json
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingWithCallbacks.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-913

#916 Fix functional tests
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.aat.template.yaml
  charts/em-ccdorc/values.preview.template.yaml
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-916

#917 Ignored all tests to investigate callBackUrl issue
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-917

#918 Added in dependabot config
  .github/dependabot.yml
  .github/stale.yml
  renovate.json
Labels: ns:em, prd:em, rel:em-ccdorc-pr-918

#929 Merged bot prs in to one
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-929

#930 Merged bot prs in to one
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-930

#938 Merged bot prs in to one
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/JacksonConfiguration.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-938

#943 Use em-test-helper version 1.21.4
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-943

#946 Em-4227 save app connection to keyvault
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-ccdorc-pr-946

#948 EM-4227 fix pitest
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-948

#954 [EM-4609]-EM-CCD-Orchestrator-CVE-Fix
  build.gradle
Labels: ns:em, prd:em, em-ccd-orchestrator-cve-fix, rel:em-ccdorc-pr-954

#953 Change response status code
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleControllerTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-953
