Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-02, with the labels that each got.

#819 Resolve CVE's
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-819

#826 Fix CWE-862
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-826

#821 Update helm chart
  charts/em-ccdorc/Chart.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-821

#827 Removed suppression
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-827
