Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-05, with the labels that each got.

#871 EM4386: Update the sonar exclusions
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackController.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-871

#882 Updated config for Renovate Bot
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-ccdorc-pr-882

#886 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-886

#888 Removed dependabot config
  .github/dependabot.yml
  .github/stale.yml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-888
