Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-08, with the labels that each got.

#901 Add case id to document tasks
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdCloneScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CdamDetailsDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/CdamDto.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-901

#904 Use document task id and polling to test async stitch
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/aat/resources/application.yml
  src/aat/resources/custom-documents-case.json
  src/aat/resources/multi-bundle-case.json
  src/aat/resources/non-custom-documents-case.json
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackResponseDto.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutorTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-904

#906 DO NOT MERGE : Removed redundant fields
  .env
Labels: ns:em, prd:em, rel:em-ccdorc-pr-906

#909 Resolved fortify issue
  docker-compose-dependencies.yml
  docker-compose.yml
  docker-pactbroker-compose.yml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-909

#910 Resolve service exception
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspect.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-910
