Repository hmcts/em-ccd-orchestrator, pull requests merged in 2022-07, with the labels that each got.

#897 Added in changes for CFTLib
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/aat/resources/application.yml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-897

#898 Update README.md
  README.md
Labels: ns:em, prd:em, rel:em-ccdorc-pr-898

#902 Added in more logs to troubleshoot prod issue
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-902

#903 Updated the logic to populate the cdam details
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/CdamDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/DocumentTaskDTO.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutorTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-903

#905 Updated springboot version & removed redundant cve suppression
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-905
