Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-08, with the labels that each got.

#1261 RET-3917 - Onboard ET and ECM to EM Bundling tools
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bundleconfiguration/et-dcf-2.yaml
  src/main/resources/bundleconfiguration/et-dcf-ordered.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1261

#1264 CVI-7950 update case progression yaml
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1264

#1265 ST-1388 documentType to category_id
  src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1265

#1266 em-5488: added 1 fingerprint to audit.json
  audit.json
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1266

#1271 Feat/civ 7950
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: prd:em, add-or-update, ns:em, rel:em-ccdorc-pr-1271

#1278 CIV-7950 remove filename and corrected CL2 disclosure file name
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1278

#1279 CIV-7950 update file name
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1279
