Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-09, with the labels that each got.

#1281 CIV-7950 fix file name
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1281

#1288 add log
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1288

#1289 Updated log level
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1289

#1291 Add exception type
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingTaskMaxRetryException.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1291

#1296 ST-1388 Refactoring category_id to categoryId
  src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1296

#1298 Update Renovate config
  .github/renovate.json
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1298

#1322 Em 5551 update renovate config
  .github/dependabot.yml
  .github/stale.yml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1322

#1323 ST-1388 Refactoring st_cic Bundle yaml config
  src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1323

#1324 Em 5551 update renovate config
  .github/renovate.json
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1324

#1326 ST-1388 Fixing typo
  src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1326

#1327 Em 5551 update renovate config
  .github/renovate.json
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1327

#1332 fix renovate EM-5551
  .github/renovate.json
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1332
