Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-01, with the labels that each got.

#1044 EM-4912-suppress-vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1044

#1038 Initial yaml config
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1038

#1051 Feat/civ 5796
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1051

#1054 Suppress CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1054

#1055 EM-4943 suppress vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1055

#1056 Feat/civ 5796
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1056

#1042 PRLBundle changes(READY FOR MERGE)
  src/main/resources/bundleconfiguration/prl-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1042

#1057 Feat/civ 5796
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1057

#1059 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1059

#1069 Feat/civ 5796
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1069
