Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-05, with the labels that each got.

#1178 EM-5230 avoid CVE-2023-20862
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1178

#1181 CIV-7573 add testing changes
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1181

#1182 Refer to new AppInsights details
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-ccdorc-pr-1182

#1191 RIA-6979: iac-hearing-bundle-config file fixed
  src/main/resources/bundleconfiguration/iac-hearing-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1191

#1193 Removed log line
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
Labels: ns:em, prd:em, add-or-update, rel:em-ccdorc-pr-1193

#1195 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1195

#1196 ST-1388 ST CIC bundle config file
  src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1196

#1198 EM-5117 spring 3 upgrade- remove javax.el
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1198

#1199 EM-5117 spring 3 upgrade- remove spring boot test from smoke test
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/smoke/SmokeTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1199

#1200 EM-5117 spring 3- arrange jackson dependency
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1200

#1202 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1202
