Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-06, with the labels that each got.

#1209 EM-5300 override appinsight access
  charts/em-ccdorc/values.preview.template.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1209

#1180 Spring 3 upgrade
  build.gradle
  config/owasp/dependency-check-suppressions.xml
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureStitchingCompleteScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/TestConfig.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/Pair.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/aat/resources/conf/logback.xml
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/Application.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyHttpServletRequest.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyServletInputStream.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ContentCachingFilter.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/InputValidationException.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoCreator.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/DocumentTaskDTO.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommandTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/TestSecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyServletInputStreamUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ContentCachingFilterUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java
  src/test/resources/logback.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1180

#1227 Resolved CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1227

#1230 Jaxb error
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1230
