Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-10, with the labels that each got.

#1350 Suppress CVE-2023-4586
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1350

#1356 EM-5591 remove DEBUG APPLICATIONINSIGHTS INSTRUMENTATION
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1356

#1361 EM-5616 CVE-2023-5072-vulnerability
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1361

#1367 EM-5505 reduce logs
  lib/applicationinsights.json
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1367

#1368 EM-5505 reduce welcome logs
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1368
