Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-04, with the labels that each got.

#1161 update case progression config
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: ns:em, prd:em, add-or-update, rel:em-ccdorc-pr-1161

#1159 EM-5186 remove security.sh
  security.sh
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1159

#1162 EM-5186 suppress security vulnerability
  audit.json
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1162

#1166 EM-5198 security scan
  audit.json
  functional-output/zap.reports
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1166

#1169 Em 5193 endpoint to return json
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/smoke/SmokeTest.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/WelcomeController.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/WelcomeControllerTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1169
