Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-03, with the labels that each got.

#1129 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1129

#1133 Updated CVE list
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1133

#1136 CIV-7573 corrected typos
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1136

#1108 Em-5067 refactor ccd update
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiEventCreator.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdUpdateService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoCreator.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/StitchingCompleteCallbackService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CCDUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiEventCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/StitchingCompleteCallbackServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java
  src/test/resources/config/application.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1108

#1140 Investigate cdam validation
  Jenkinsfile_CNP
  build.gradle
  charts/em-ccdorc/values.preview.template.yaml
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoCreator.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoCreatorTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1140

#1154 EM-5170-avoid-vulnerability
  Dockerfile
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1154
