Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-11, with the labels that each got.

#1377 ECM - Changed service name
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
  src/main/resources/application.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1377

#1379 CIV-11132 change section of Particulars of Claim
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1379

#1383 EM-5649 fix app insight logging
  Dockerfile
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1383

#1387 RET-3917 Update et-dcf-2.yaml
  src/main/resources/bundleconfiguration/et-dcf-2.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1387

#1390 Stop 403 showing for other error codes
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/errors/ExceptionTranslator.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/errors/ExceptionTranslatorIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/errors/ExceptionTranslatorTestController.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1390

#1406 CIV-11132 Directions Questionnaires
  src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml
Labels: prd:em, add-or-update, ns:em, rel:em-ccdorc-pr-1406

#1412 EM-5691 add error log
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
  src/test/resources/case-data7.json
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1412
