Repository hmcts/em-ccd-orchestrator, pull requests merged in 2023-07, with the labels that each got.

#1228 Em-5118 remove "/" from URL
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1228

#1237 Upgraded gradle version to 8
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1237

#1251 upgrade spring boot to 3.1.2
  build.gradle
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1251

#1254 update checkstyle
  build.gradle
  config/checkstyle/checkstyle.xml
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdCloneScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdCloneScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureStitchingCompleteScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/StitchingCompleteScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/Application.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/CliApplication.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/ConfigurationLoader.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoader.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdValue.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/StitchingCompleteCallbackService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/CallbackDto.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/HttpOkResponseCloser.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutorTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/CallbackUrlCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoaderTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/TestSecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyServletInputStreamUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleCloningServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CCDUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDtoTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCaseDataContentTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/StitchingCompleteCallbackServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/mapper/StitchingDTOMapperTest.java
Labels: ns:em, prd:em, rel:em-ccdorc-pr-1254
