Repository hmcts/em-ccd-orchestrator, pull requests merged in 2024-11, with the labels that each got.

#1761 EM-6301 add violations to exception message
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/InputValidationException.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1761

#1762 FPET-1174: Add FM5 statements to sample-config.yaml
  src/main/resources/bundleconfiguration/sample-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1762

#1766 FPET-1174: Add FM5 statements to prl-bundle-config.yaml
  src/main/resources/bundleconfiguration/prl-bundle-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1766

#1768 whitelisted civil_general_applications
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1768

#1770 SSCSCI-1381
  src/main/resources/bundleconfiguration/sscs-ib-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-ib-bundle-edited-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1770

#1769 DTSCCI-1155: adding civil form config to use async stitch call
  src/main/resources/bundleconfiguration/civil-forms-bundle-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1769

#1771 DTSCCI-1155: Access for civil to keyvault in aat
  infrastructure/aat.tfvars
Labels: prd:em, ns:em, aat/add-or-update, prod/no-changes, rel:em-ccdorc-pr-1771

#1783 Upgrade Serenity to 4.2.9
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/smoke/SmokeTest.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1783

#1784 Upgrade POI to 5.2.5
  build.gradle
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1784

#1785 Upgrade pact to 4.6.15
  build.gradle
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1785

#1787 IdamConsumerTest moved back to V3 pact spec
  src/contractTest/java/uk/gov/hmcts/reform/em/orchestrator/IdamConsumerTest.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1787
