Repository hmcts/em-ccd-orchestrator, pull requests merged in 2024-05, with the labels that each got.

#1580 Disabled Spot instances.
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1580

#1577 RIA-8846 Include the existing files from reheard bundle in the remitt…
  src/main/resources/bundleconfiguration/iac-remitted-reheard-hearing-bundle-config.yaml
Labels: prd:em, add-or-update, ns:em, aat/add-or-update, rel:em-ccdorc-pr-1577

#1589 Revert "RIA-8846 Include the existing files from reheard bundle in th…
  src/main/resources/bundleconfiguration/iac-remitted-reheard-hearing-bundle-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1589
