Repository hmcts/em-ccd-orchestrator, pull requests merged in 2024-04, with the labels that each got.

#1556 Updated Java chart to enable HPA config
  charts/em-ccdorc/Chart.yaml
Labels: prd:em, Do Not Merge, ns:em, rel:em-ccdorc-pr-1556

#1563 RIA-8291 Updated remitted bundle config
  src/main/resources/bundleconfiguration/iac-remitted-reheard-hearing-bundle-config.yaml
Labels: prd:em, add-or-update, ns:em, aat/add-or-update, rel:em-ccdorc-pr-1563

#1568 fixed code smells
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommand.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/InputValidationException.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/mapper/StitchingDTOMapper.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommandTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingServiceTest.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1568

#1571 Updated StitchingServiceException, added BundleException
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleException.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceException.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1571
