Repository hmcts/em-ccd-orchestrator, pull requests merged in 2024-01, with the labels that each got.

#1459 Removed redundant s2s keys
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
  src/main/resources/application.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1459

#1462 ST-1388 Refactoring st_cic Bundle yaml config
  src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1462

#1463 filter -SPtribunals - Ben Guy
  src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1463

#1465 Em 5744 resolve CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1465

#1475 EM-5287 refactor test files
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/aat/resources/automated-case-invalid-configuration.json
  src/aat/resources/automated-case.json
  src/aat/resources/filename-case.json
  src/aat/resources/filename-with-51-chars.json
  src/aat/resources/missing-cdam-properties-case.json
  src/aat/resources/stitchingComplete.json
  src/main/resources/bundleconfiguration/testbundleconfiguration/example-incorrect-key.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/example-incorrect-value-for-key.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/example-with-51-chars-filename.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/example-with-documents.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/example-with-filename.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/example.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-1-flat-docs.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-10-sorting.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-11-sorting.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-12-invalid-document-property.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-13-render-image-flat-docs.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-2-filter-flat-docs.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-3-foldered-docs.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-4-filtered-foldered-docs.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-5-invalid-url.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-6-has-typo.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-7-not-a-single-doc.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-8-not-an-array.yaml
  src/main/resources/bundleconfiguration/testbundleconfiguration/f-tests-9-multiple-filters.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoaderTest.java
  src/test/resources/documents-case.json
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1475

#1480 Em-5287 add test
  src/main/resources/bundleconfiguration/testbundleconfiguration/custom-bundle-wrong-config.yaml
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoaderTest.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1480

#1485 add graceful shutdown
  src/main/resources/application.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1485

#1486 EM-5786 fix checkstyle
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingTaskMaxRetryException.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/errors/ExceptionTranslatorTestController.java
Labels: prd:em, ns:em, no-changes, rel:em-ccdorc-pr-1486

#1490 Upgrading to java 21
  build.gradle
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1490

#1491 EM-5801 - bump pitest plugin
  build.gradle
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1491
