Repository hmcts/em-ccd-orchestrator, pull requests merged in 2024-07, with the labels that each got.

#1645 use dummy default key
  src/aat/resources/application.yml
  src/main/resources/application.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1645

#1655 Fix code smell by removing duplicate code chunk
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/UpdateCase.java
Labels: prd:em, ns:em, aat/no-changes, prod/no-changes, rel:em-ccdorc-pr-1655

#1658 EM-5923 Code smells: protected constructor
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/UpdateCase.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1658
