Repository hmcts/em-ccd-orchestrator, pull requests merged in 2024-10, with the labels that each got.

#1708 local setup
  src/aat/resources/application.yml
  src/main/resources/application.yaml
Labels: prd:em, ns:em, aat/no-changes, prod/no-changes, rel:em-ccdorc-pr-1708

#1737 FPET-995: Copy bundle config from sample-config to prl-bundle-config
  src/main/resources/bundleconfiguration/prl-bundle-config.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1737

#1756 check for in progress
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
  src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1756
