Repository hmcts/em-ccd-orchestrator, pull requests merged in 2025-01, with the labels that each got.

#1818 reinstate whitelist for xui webapp
  charts/em-ccdorc/Chart.yaml
  charts/em-ccdorc/values.yaml
  src/main/resources/application.yaml
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1818

#1810 migrate unit tests to junit 5
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutorTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/CallbackUrlCreatorTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommandTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoaderTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/mapper/StitchingDTOMapperTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilitiesTest.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1810

#1812 migrate unit tests to junit 5 part 3
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyHttpServletRequestUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyServletInputStreamUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ContentCachingFilterUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDtoTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdaterTest.java
  src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/StitchingCompleteCallbackServiceTest.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1812

#1815 migrate functional tests to junit 5
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingWithCallbacksTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/BaseTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdCloneScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdPrehookScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/OpenIdConnectScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingWithCallbacks.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingWithCallbacksTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdCloneScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdPrehookScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureStitchingCompleteScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/StitchingCompleteScenariosTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/smoke/SmokeTest.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1815

#1823 remove junit vintage engine
  build.gradle
Labels: prd:em, ns:em, rel:em-ccdorc-pr-1823

#1832 Add ET to MI to use in preview
  infrastructure/aat.tfvars
Labels: prd:em, ns:em, aat/add-or-update, prod/no-changes

#1831 upgrade em-test-helper to 2.1.1
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/BaseTest.java
Labels: prd:em, ns:em, prod/no-changes

#1840 SSCSCI-1548 updating bundle config post-release
  src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
  src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
Labels: prd:em, ns:em
